version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: legacy_postgres
    environment:
      POSTGRES_DB: legacy_modernization_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - legacy_network

  redis:
    image: redis:7-alpine
    container_name: legacy_redis
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - legacy_network

  adminer:
    image: adminer
    container_name: legacy_adminer
    ports:
      - "8080:8080"
    networks:
      - legacy_network
    depends_on:
      - postgres

volumes:
  postgres_data:
  redis_data:

networks:
  legacy_network:
    driver: bridge